# SBERT Sentence Analysis

## 1. Preparations

### 1.1 Read Data
The sentence data were preprocessed (see preprocessing.ipynb)
In the dataframe:  
- "sentence" = preprocessed sentences with placeholders of anonymized information, **used for the analysis**
- "clean_sentence" = proprocessed sentences with placeholders removed,  
- "translated_sentence" = translated from "sentence" column to English with translate.ipynb

In [2]:
import pandas as pd
# read the sentence data 
df = pd.read_excel("/workspace/persistent/mijnidbcoachnlp/data/analysis_data/sentence_data_for_analysis.xlsx", index_col=0)
sentences = df["sentence"].to_list()

# check the df head
df.head()

,message_id,sentence,clean_sentence,sentence_id,translated_sentence
0,1,"Geachte ibd groep, Is mijn uitslag al binnen ...","ibd groep, Is mijn uitslag al binnen van de b...",1,"Dear Ibd group, has my results come back from ..."
1,3,Vorige week is door [ZIEKENHUIS] [LOCATIE] mij...,Vorige week is door mijn ontlasting onderzoc...,2,Last week my stool was examined by [SIGHSHOUSE...
2,3,Graag zou ik de uitkomst hiervan vernemen.,Graag zou ik de uitkomst hiervan vernemen.,3,I would like to hear the outcome of this.
3,4,bloed in de ontlasting wordt steeds meer en st...,bloed in de ontlasting wordt steeds meer en st...,4,blood in the stool is becoming more and more f...
4,4,Ligt dit aan de medicatie?,Ligt dit aan de medicatie?,5,Is this because of the medication?

In [3]:
# check input size
len_data = len(sentences)
print(f"data size: {len_data}")

data size: 41119

### 1.2. Import the list of stopwords
The stopwords are extended with a customized set which contains weekdays, months and titles for the IBD doctors because they are usually found in the texts about appointments but create noise in the topic representations

In [3]:
### Importing the list of Dutch stopwords (note that there are customized dutch words in there)

with open('/workspace/persistent/mijnidbcoachnlp/data/analysis_data/stopwords_extended.txt', 'r') as file:
    lines = [line.strip() for line in file.readlines()]

dutch_stopwords = lines

### 1.3 Embed the lists of sentences (Commented Out)
In this section, we embed the sentence data with five differen sentence transformer models available on Hugging Face. Only run once.

#### 1.3.1. sentence-transformers/distiluse-base-multilingual-cased-v1

In [11]:
from sentence_transformers import SentenceTransformer
from tqdm.autonotebook import tqdm  
import numpy as np
import sentence_transformers.util
#sentence_transformers.util.tqdm = tqdm

#embedding_model = SentenceTransformer("distiluse-base-multilingual-cased-v1")
# Generate and save embeddings
#embeddings = embedding_model.encode(sentences, show_progress_bar=True)
#np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v1_sentence_placeholder.npy', embeddings)

#### 1.3.2. sentence-transformers/distiluse-base-multilingual-cased-v2

In [12]:
#embedding_model = SentenceTransformer("distiluse-base-multilingual-cased-v2")
# Generate and save embeddings
#embeddings = embedding_model.encode(sentences, show_progress_bar=True)
#np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v2_sentence_placeholder.npy', embeddings)

#### 1.3.3. NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers

In [13]:
#embedding_model = SentenceTransformer("NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers")
# Generate and save embeddings
#embeddings = embedding_model.encode(sentences, show_progress_bar=True)
# np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_robbert2022_sentence_placeholder.npy', embeddings)

#### 1.3.4. sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

In [14]:
#embedding_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
#embeddings = embedding_model.encode(sentences, show_progress_bar=True)
#np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy', embeddings)

#### 1.3.5. sentence-transformers/paraphrase-multilingual-mpnet-base-v2

In [15]:
# embedding_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-mpnet-base-v2")
# embeddings bin= embedding_model.encode(sentences, show_progress_bar=True)
# np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_mpnet_v2_sentence_placeholder.npy', embeddings)

#### 1.3.6. Alibaba-NLP/gte-Qwen2-7B-instruct

In [4]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("intfloat/multilingual-e5-large-instruct", trust_remote_code=True)
embeddings = embedding_model.encode(sentences, show_progress_bar=True)

Batches: 100%|██████████| 1285/1285 [20:04<00:00,  1.07it/s]

NameError: name 'np' is not defined

In [5]:
import numpy as np

np.save('/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_intfloat.npy', embeddings)

### 1.4 Load embeddings

In [5]:
import numpy as np
from sentence_transformers import SentenceTransformer

# Define each embedding model using SentenceTransformer
embedding_model_stv1 = SentenceTransformer("distiluse-base-multilingual-cased-v1")  # Adjust model name if needed
embedding_model_stv2 = SentenceTransformer("distiluse-base-multilingual-cased-v2")
embedding_model_stmini = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")  # Adjust this if needed
embedding_model_stmp = SentenceTransformer("sentence-transformers/paraphrase-multilingual-mpnet-base-v2")  # Adjust if you have a different MPNet variant
embedding_model_strob = SentenceTransformer("NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers")  # Adjust based on the RobBERT model you are using
embedding_model_e5 = SentenceTransformer("intfloat/multilingual-e5-large-instruct", trust_remote_code=True)

embeddings_stv1 = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v1_sentence_placeholder.npy")
embeddings_stv2 = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v2_sentence_placeholder.npy")
embeddings_stmini = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy")
embeddings_stmp = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_mpnet_v2_sentence_placeholder.npy")
embeddings_strob = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_robbert2022_sentence_placeholder.npy")
embeddings_e5 = np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_e5.npy")

In [6]:
# disable parallelism to avoid some warnings
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

## 2. Fit the models

### 2.1 Initialize BERTopic settings fixed configurations

In [28]:
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.representation import KeyBERTInspired

# Shared settings (avoid code duplication)
bertopic_settings = {
    "umap_model": UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=42), # fixed random_state for reproducibility
    "hdbscan_model": HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=False),
    "vectorizer_model": CountVectorizer(stop_words=dutch_stopwords, min_df=2, ngram_range=(1, 1), token_pattern=r'\b[a-zA-Z]{3,}\b'),
    "calculate_probabilities": False,
    "verbose": True
    #"representation_model": { 
    #    "KeyBERTInspired": KeyBERTInspired()
        #...
    #}
}

### 2.2 Run models with different embeddings and save the models

In [48]:

# Define model names and embeddings
models_and_embeddings = [
    ("stv1", SentenceTransformer("distiluse-base-multilingual-cased-v1"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v1_sentence_placeholder.npy")),
    ("stv2", SentenceTransformer("distiluse-base-multilingual-cased-v2"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_v2_sentence_placeholder.npy")),
    ("mini", SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_miniL12v2_sentence_placeholder.npy")),
    ("mpnet", SentenceTransformer("sentence-transformers/paraphrase-multilingual-mpnet-base-v2"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_mpnet_v2_sentence_placeholder.npy")),
    ("robbert", SentenceTransformer("NetherlandsForensicInstitute/robbert-2022-dutch-sentence-transformers"), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_st_robbert2022_sentence_placeholder.npy")),
    ("e5", SentenceTransformer("intfloat/multilingual-e5-large-instruct", trust_remote_code=True), np.load("/workspace/persistent/mijnidbcoachnlp/data/embeddings/embeddings_e5.npy"))
]

In [31]:
# DO NOT RUN
# fit all the models once 
from bertopic import BERTopic

for name, embedding_model, embeddings in models_and_embeddings:
    print(f"Training model: {name}")

    # Train BERTopic
    topic_model = BERTopic(**bertopic_settings)
    topics, probs = topic_model.fit_transform(documents=sentences, embeddings=embeddings)

    # Optional: Save the model
    topic_model.save(f"/workspace/persistent/mijnidbcoachnlp/saved_models/st_models_for_comparison/{name}_base", serialization="pytorch", save_ctfidf=True, save_embedding_model=embedding_model)

print("Finished.")

2025-05-20 11:27:13,259 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

Training model: stv1

2025-05-20 11:28:10,217 - BERTopic - Dimensionality - Completed ✓
2025-05-20 11:28:10,220 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-20 11:28:13,028 - BERTopic - Cluster - Completed ✓
2025-05-20 11:28:13,044 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-05-20 11:28:14,004 - BERTopic - Representation - Completed ✓
2025-05-20 11:28:15,134 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

Training model: stv2

2025-05-20 11:29:11,962 - BERTopic - Dimensionality - Completed ✓
2025-05-20 11:29:11,965 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-20 11:29:13,758 - BERTopic - Cluster - Completed ✓
2025-05-20 11:29:13,773 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-05-20 11:29:14,730 - BERTopic - Representation - Completed ✓
2025-05-20 11:29:15,799 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

Training model: mini

2025-05-20 11:30:11,167 - BERTopic - Dimensionality - Completed ✓
2025-05-20 11:30:11,170 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-20 11:30:13,054 - BERTopic - Cluster - Completed ✓
2025-05-20 11:30:13,070 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-05-20 11:30:14,065 - BERTopic - Representation - Completed ✓
2025-05-20 11:30:15,261 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

Training model: mpnet

2025-05-20 11:31:14,473 - BERTopic - Dimensionality - Completed ✓
2025-05-20 11:31:14,476 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-20 11:31:16,475 - BERTopic - Cluster - Completed ✓
2025-05-20 11:31:16,491 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-05-20 11:31:17,526 - BERTopic - Representation - Completed ✓
2025-05-20 11:31:18,774 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

Training model: robbert

2025-05-20 11:32:18,664 - BERTopic - Dimensionality - Completed ✓
2025-05-20 11:32:18,667 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-20 11:32:20,327 - BERTopic - Cluster - Completed ✓
2025-05-20 11:32:20,343 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-05-20 11:32:21,387 - BERTopic - Representation - Completed ✓
2025-05-20 11:32:22,617 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

Training model: e5

2025-05-20 11:33:25,908 - BERTopic - Dimensionality - Completed ✓
2025-05-20 11:33:25,911 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-20 11:33:27,853 - BERTopic - Cluster - Completed ✓
2025-05-20 11:33:27,868 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-05-20 11:33:28,859 - BERTopic - Representation - Completed ✓

Finished.

## 3. Load base models for tuning

In [37]:
from bertopic import BERTopic

base_models = {}
for name, embedding_model, embeddings in models_and_embeddings:
    path = f"/workspace/persistent/mijnidbcoachnlp/saved_models/st_models_for_comparison/{name}_base"
    loaded_model = BERTopic.load(path, embedding_model=None)
    base_models[name] = loaded_model

print("Finished.")

Finished.

In [46]:
# check the topic information of "stv1", "stv2", "mini", "mpnet", "robbert", and "e5"
base_models['e5'].get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,19479,-1_last_pijn_weet_buikpijn,"[last, pijn, weet, buikpijn, ziekenhuis, afspr...",NaN
1,0,522,0_poli_afspraak_telefonische_staan,"[poli, afspraak, telefonische, staan, consult,...",NaN
2,1,486,1_slijm_bloed_ontlasting_soms,"[slijm, bloed, ontlasting, soms, helder, bloed...",NaN
3,2,484,2_calprotectine_calpro_thuistest_waarde,"[calprotectine, calpro, thuistest, waarde, tes...",NaN
4,3,482,3_endoscopie_darmonderzoek_coloscopie_colonscopie,"[endoscopie, darmonderzoek, coloscopie, colons...",NaN
...,...,...,...,...,...
338,337,15,337_normaal_den_doorgaans_makkelijk,"[normaal, den, doorgaans, makkelijk, nagenoeg,...",NaN
339,338,15,338_vragenlijst_ingevuld_invullen_vragenlijsten,"[vragenlijst, ingevuld, invullen, vragenlijste...",NaN
340,339,15,339_blaasontsteking_ontdekken_gegeten_virusinf...,"[blaasontsteking, ontdekken, gegeten, virusinf...",NaN
341,340,15,340_ups_downs_gaat_gewichtsverlies,"[ups, downs, gaat, gewichtsverlies, vertrouwen...",NaN
342,341,15,341_leeftijd_jaar_halfjaar_project,"[leeftijd, jaar, halfjaar, project, maand, int...",NaN

In [70]:
searched_topics = base_models["stv1"].find_topics(search_term="bloed", image=None, top_n=5)
searched_topics

([0, 311, 183, 82, 202],
 [0.56670856, 0.30812782, 0.24840379, 0.19421884, 0.1939101])

In [71]:
topic_info = base_models["stv1"].get_topic_info()
topic_info[topic_info['Topic'].isin(searched_topics[0])]

,Topic,Count,Name,Representation,Representative_Docs
1,0,3353,0_bloed_prikken_bloedprikken_slijm,"[bloed, prikken, bloedprikken, slijm, bloeduit...",NaN
83,82,74,82_ijzer_vit_laag_ampullen,"[ijzer, vit, laag, ampullen, injecties, heen, ...",NaN
184,183,32,183_vitamine_vitamines_metoprol_vastgelegd,"[vitamine, vitamines, metoprol, vastgelegd, ca...",NaN
203,202,28,202_urine_urineweginfectie_gecontroleerd_bacterin,"[urine, urineweginfectie, gecontroleerd, bacte...",NaN
312,311,17,311_magnesium_fosfatase_alat_hemoglobine,"[magnesium, fosfatase, alat, hemoglobine, mcv,...",NaN