# Data Cleaning (Start From Here)

In [67]:
# read the original anonymized dataframe
import pandas as pd
df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_data/anonymized_berichten.xlsx")

In [68]:
len(set(df["UserGUID"].iloc[2:].to_list()))

856

In [69]:
len(df[["Message"]][2:]) # Number of messages = 33237

33237

In [70]:
len(df["Message"][df["richting (van of naar cliënt)"] == 'From client'])
# number of messages sent from patients = 13199

13199

In [71]:
# drop duplicated messages IF they are from the same user
df = df.drop_duplicates(subset=['UserGUID', 'Message'], keep='first')

In [72]:
len(df["Message"][df["richting (van of naar cliënt)"] == 'From client']) # Now there are 12754 messages left

12754

### Step 1. Remove html tags from the messages

In [73]:
# clean up the html tags
from bs4 import BeautifulSoup
def clean_html_with_soup(text):
    soup = BeautifulSoup(text, 'html.parser')
    return soup.get_text()

df['Message'] = df['Message'].apply(lambda x: clean_html_with_soup(str(x)))

/tmp/ipykernel_284827/1416969809.py:4: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(text, 'html.parser')

In [74]:
df=df[2:]

In [75]:
df = df.reset_index()
df["Message_ID"] = df.index
df=df.drop(columns=["index"])
df

,ProviderName,ProgramName,UserGUID,Datum/tijd,Message,richting (van of naar cliënt),Verzender indien naar cliënt,Message_ID
0,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-01-14 16:34:16.323,"Goedemiddag, Dank voor uw aanmelding en het invullen van de eerste vragenlijst. De eerste 3 ma...",To client,miacilissen,0
1,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-02-10 12:46:36.230,"Beste gebruikers van mijnIBDcoach, Van 11 februari t/m 16 februari is het mogelijk dat uw beri...",To client,isour1_mumc,1
2,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-03-02 08:38:01.253,"Beste gebruiker van mijnIBDcoach, In verband met de vele vragen over het Coronavirus, sturen w...",To client,isour1_mumc,2
3,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 15:49:29.733,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON-1] in [LOCATIE-1] met verdenking van ...,From client,NaN,3
4,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 16:23:42.457,"Goedemiddag, Bedankt voor uw bericht. We zullen de bloeduitslagen en calprotectine bepaling op...",To client,isour1_mumc,4
...,...,...,...,...,...,...,...,...
32682,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-04 15:17:48.923,"A.U.B. NIET REAGEREN OP DIT BERICHT Beste gebruiker van mijnIBDcoach, De nieuwe mijnIBDcoach i...",To client,mumcibd_support,32682
32683,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-22 14:01:17.450,"A.U.B. NIET REAGEREN OP DIT BERICHT Beste gebruiker van mijnIBDcoach, Sinds kort kunt u gebrui...",To client,isour1_mumc,32683
32684,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-01-11 11:35:02.663,"AUB NIET REAGEREN OP DIT BERICHT Beste gebruiker van mijnIBDcoach, Eind oktober is de nieuwe v...",To client,mumcibd_support,32684
32685,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-04-11 18:13:23.077,VRAGENLIJST FACTOREN UIT HET DAGELIJKSE LEVEN EN IBD Als je een chronische ontstekingsziekte i...,To client,mpierik_mumc,32685
32686,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-05-17 12:22:41.187,"Dag,Uit onderzoek blijkt dat bepaalde factoren uit je dagelijks leven een rol kunnen spelen bij ...",To client,miacilissen,32686

In [76]:
column_to_move = 'Message_ID'
new_column_order = [column_to_move] + [col for col in df.columns if col != column_to_move]

# Reorder the DataFrame columns
df = df[new_column_order]
#df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/message_data.xlsx")
df

,Message_ID,ProviderName,ProgramName,UserGUID,Datum/tijd,Message,richting (van of naar cliënt),Verzender indien naar cliënt
0,0,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-01-14 16:34:16.323,"Goedemiddag, Dank voor uw aanmelding en het invullen van de eerste vragenlijst. De eerste 3 ma...",To client,miacilissen
1,1,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-02-10 12:46:36.230,"Beste gebruikers van mijnIBDcoach, Van 11 februari t/m 16 februari is het mogelijk dat uw beri...",To client,isour1_mumc
2,2,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-03-02 08:38:01.253,"Beste gebruiker van mijnIBDcoach, In verband met de vele vragen over het Coronavirus, sturen w...",To client,isour1_mumc
3,3,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 15:49:29.733,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON-1] in [LOCATIE-1] met verdenking van ...,From client,NaN
4,4,MUMC MijnIBDcoach,MijnIBDcoach4.0,72BF6AE2-1568-4843-A234-51A9F5598B80,2020-07-28 16:23:42.457,"Goedemiddag, Bedankt voor uw bericht. We zullen de bloeduitslagen en calprotectine bepaling op...",To client,isour1_mumc
...,...,...,...,...,...,...,...,...
32682,32682,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-04 15:17:48.923,"A.U.B. NIET REAGEREN OP DIT BERICHT Beste gebruiker van mijnIBDcoach, De nieuwe mijnIBDcoach i...",To client,mumcibd_support
32683,32683,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2021-11-22 14:01:17.450,"A.U.B. NIET REAGEREN OP DIT BERICHT Beste gebruiker van mijnIBDcoach, Sinds kort kunt u gebrui...",To client,isour1_mumc
32684,32684,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-01-11 11:35:02.663,"AUB NIET REAGEREN OP DIT BERICHT Beste gebruiker van mijnIBDcoach, Eind oktober is de nieuwe v...",To client,mumcibd_support
32685,32685,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-04-11 18:13:23.077,VRAGENLIJST FACTOREN UIT HET DAGELIJKSE LEVEN EN IBD Als je een chronische ontstekingsziekte i...,To client,mpierik_mumc
32686,32686,MUMC MijnIBDcoach,MijnIBDcoach5.0,BC3E4A89-8869-4663-9240-0A7C8FE5C008,2022-05-17 12:22:41.187,"Dag,Uit onderzoek blijkt dat bepaalde factoren uit je dagelijks leven een rol kunnen spelen bij ...",To client,miacilissen

### Step 2. Split the message into sentences

In [77]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [78]:
# using nltk instead of spacy
import nltk
from nltk.tokenize import sent_tokenize
import re

def split_sentence_with_matches(sentence, matches):
    
    
    parts = []
    for i in range(len(matches)):
        match = matches[i]
        part = sentence.split(match, 1)[0]
        
        if i > 0:
            part = "".join([matches[i-1], part])
        
        parts.append(part)
        remaining_part = sentence.split(match, 1)[1]
        sentence = remaining_part
    
    if remaining_part:
        part = "".join([matches[-1], remaining_part])
        parts.append(part)

    return parts


def split_sentence(sentence):
    pattern1 = r'(?<!^)Maar|En|Ik|Ze|Het'
    pattern2 = r'(?<!^)\.\s*[A-Z][a-z]+'
    matches1 = re.findall(pattern1, sentence)
    matches2 = re.findall(pattern2, sentence)
    matches = matches1
    if len(matches1) < len(matches2):
        matches = matches2
    smaller_sentences = []
    if matches:
        smaller_sentences = split_sentence_with_matches(sentence, matches)
    else:
        #print("Can't split the following sentence: ", "\n", sentence)
        pass
    return smaller_sentences


def nltk_split_into_sentences(df, column):
    sentence_data = []
    
    # Loop through each message in the original DataFrame
    for message_id, message in zip(df['Message_ID'], df[column]):
        sentences = sent_tokenize(message)
            
        # Append each sentence along with its existing Message_ID
        for sentence in sentences:
            
            sentence = sentence.strip()
            if len(sentence) <= 400 or 'voedinginformatie' in sentence.lower():
                sentence_data.append({'Message_ID': message_id, 'Sentence': sentence})

            else:
                #print("\nOriginal: ", "\n", sentence, "\n")
                # Call split_sentence to get smaller sentences
                smaller_sentences = split_sentence(sentence)
                
                if smaller_sentences:                    
                    for smaller_sentence in smaller_sentences:
                        smaller_sentence = re.sub(r"^[,!.?\]]*\s*", "", smaller_sentence)

                        sentence_data.append({'Message_ID': message_id, 'Sentence': smaller_sentence})

                else:
                    pass
            

    # Create a new DataFrame with the split sentences
    sentence_df = pd.DataFrame(sentence_data)

    return sentence_df

# Example usage
df_fromclient = df[df["richting (van of naar cliënt)"] == "From client"]
sentence_df_nltk = nltk_split_into_sentences(df_fromclient, column="Message")

In [79]:
sentence_df = sentence_df_nltk
sentence_df

,Message_ID,Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON-1] in [LOCATIE-1] met verdenking van ...
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen."
2,3,Het begon 1 uur na het avondeten.
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten."
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn."
...,...,...
53733,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...
53734,32679,Wat adviseert u hiermee te doen?
53735,32681,"Hoi [PERSOON-1], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder."
53736,32681,Dankjewel voor de snelle reactie!
53737,32681,"Groeten, [PERSOON-2]"

In [16]:
sentence_df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/split_sentences_before_cleaning.xlsx")

### Step 2. Clean up the sentences

In [82]:
sentence_df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_data/split_sentences_before_cleaning.xlsx", index_col=0)
sentence_df

,Message_ID,Sentence,Clean_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hart...,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen."
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten."
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn."
...,...,...,...
53733,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...
53734,32679,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?
53735,32681,"Hoi [PERSOON], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Hoi , Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder."
53736,32681,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!
53737,32681,"Groeten, [PERSOON]","Groeten,"

In [63]:
import re

def replace_numbered_patterns(text):
    text = re.sub(r'\[(\w+)-\d+\]', r'[\1]', text, flags=re.IGNORECASE)
    # Match any pattern of the form [WORD-<number>] and replace with [WORD]
    return text

# Apply the function
sentence_df['Sentence'] = sentence_df['Sentence'].apply(lambda x: replace_numbered_patterns(str(x)))

In [83]:
import re

def replace_entities(text): # notice that we did not remove anonymized entities such as [APOTHEEK] and [ZIEKENHUIS] which can be informative
    text = re.sub(r'\[persoon\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[person\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[locatie\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[url\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[telefoonnummer\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[emailadres\]', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\[datum\]', '', text, flags=re.IGNORECASE)
    # remove words in the pattern of [word] but [hospital] and [pharmacy] are kept
    # remove punctuations again
    text = re.sub(r':\)|:\(|;\)', '', text)
    text = re.sub(r"^[^\w([]+", '', text)
    return text

sentence_df['Clean_Sentence'] = sentence_df['Sentence'].apply(lambda x: replace_entities(str(x)))

In [84]:
## clean up greetings and closings in the messages
import re

greetings_pattern = r"^\s*(beste|geachte|dear|hallo|hoi|hoi hoi|goedemorgen|goede morgen|goedemiddag|goede middag|goeden avond|goedenavond|dag|hello|hi|morning|good morning|good afternoon|good evening)\s*[,!?.]*\s*"
signoffs_pattern = r"\b(best regards|regards|groe?t|groe?ten|gr|groetjes?|grtjs?|mvg|m?e?t?\s*vriendelijke?\s*gr\w*|met\s*vriendelijke?|hartelijke\s*gr\w*)\b\s*[,!?.]*\s*"

def remove_greetings(text, pattern1, pattern2):
    # Remove greetings from the beginning
    cleaned_text = re.sub(pattern1, '', text, flags=re.IGNORECASE)
    # Remove signoffs from the end
    cleaned_text = re.sub(pattern2, '', cleaned_text, flags=re.IGNORECASE)
    # Strip any leading or trailing whitespace left over after substitutions

    return cleaned_text.strip()

clean_sentences = [
    remove_greetings(msg, greetings_pattern, signoffs_pattern) 
    for msg in sentence_df["Clean_Sentence"].to_list()
]

sentence_df["Clean_Sentence"] = clean_sentences

In [85]:
sentence_df

,Message_ID,Sentence,Clean_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hart...,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen."
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten."
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn."
...,...,...,...
53733,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...
53734,32679,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?
53735,32681,"Hoi [PERSOON], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Oke, dat is iig al een geruststelling ik wacht de uitslag even af verder."
53736,32681,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!
53737,32681,"Groeten, [PERSOON]",

In [86]:
# save df
sentence_df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/sentence_data_before_merging.xlsx")

### Merge incorrectly split sentences

In [87]:
sentence_df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_data/sentence_data_before_merging.xlsx", index_col=0)
sentence_df.head()

,Message_ID,Sentence,Clean_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hart...,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen."
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten."
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn."

In [92]:
# find sentences ending in ""
abbreviation_pattern = r"\b[a-zA-Z]\.[a-zA-Z]\.[a-zA-Z]\.\s*$"
abbreviation_pattern_2 = r"incl\.\s*$"

In [96]:
sentence_df = sentence_df.dropna(subset=['Clean_Sentence'])
sentence_df

,Message_ID,Sentence,Clean_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hart...,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen."
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten."
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn."
...,...,...,...
53732,32679,"Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan.","Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan."
53733,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...
53734,32679,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?
53735,32681,"Hoi [PERSOON], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Oke, dat is iig al een geruststelling ik wacht de uitslag even af verder."
53736,32681,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!

In [98]:
sentence_df = sentence_df.reset_index(drop=True)

In [99]:
to_drop = []
for i, row in sentence_df[:-1].iterrows():
    sentence = row["Clean_Sentence"]
    if re.search(abbreviation_pattern, sentence, flags=re.IGNORECASE):
        sentence_df.loc[i, "Clean_Sentence"] += " " + sentence_df.loc[i + 1, "Clean_Sentence"]
        sentence_df.loc[i, "Sentence"] += " " + sentence_df.loc[i + 1, "Sentence"]

        to_drop.append(i + 1)

# Drop merged sentences from DataFrame
sentence_df.drop(to_drop, inplace=True)

# Reset index
sentence_df.reset_index(drop=True, inplace=True)

In [100]:
len(sentence_df)

45508

In [101]:
to_drop = []
for i, row in sentence_df[:-1].iterrows():
    sentence = row["Clean_Sentence"]
    if re.search(abbreviation_pattern_2, sentence, flags=re.IGNORECASE):
        sentence_df.loc[i, "Clean_Sentence"] += " " + sentence_df.loc[i + 1, "Clean_Sentence"]
        sentence_df.loc[i, "Sentence"] += " " + sentence_df.loc[i + 1, "Sentence"]

        to_drop.append(i + 1)

# Drop merged sentences from DataFrame
sentence_df.drop(to_drop, inplace=True)

# Reset index
sentence_df.reset_index(drop=True, inplace=True)

In [102]:
len(sentence_df)

45499

In [103]:
# check if there are uncleaned leading punctuations
import re

def clean_leading_puncs(text): 

    # remove punctuations again
    text = re.sub(r"^[^\w([]+", '', text)
    return text

sentence_df['Clean_Sentence'] = sentence_df['Clean_Sentence'].apply(lambda x: clean_leading_puncs(str(x)))

In [104]:
pd.set_option("max_colwidth", 100)
sentence_df[sentence_df["Clean_Sentence"].str.contains("incl.")]

,Message_ID,Sentence,Clean_Sentence
2466,1746,:( Is het te doen om een nieuwe set te sturen van de onderzoeken die nodig zijn (incl. calprote...,Is het te doen om een nieuwe set te sturen van de onderzoeken die nodig zijn (incl. calprotectin...
3534,2382,"Hi [PERSOON] / [PERSOON], ik ga 12 juli naar een festival voor meerdere dagen inclusief camping.",ik ga 12 juli naar een festival voor meerdere dagen inclusief camping.
3654,2473,Als het goed is zijn dit de medicijnen met de aantal keren per dag; Loperamide 12x dag Psylliumv...,Als het goed is zijn dit de medicijnen met de aantal keren per dag; Loperamide 12x dag Psylliumv...
4114,2787,"Goedemorgen, Ik heb vanmorgen telefonisch contact gehad met [PERSOON] waarbij ik de uitslag van...",Ik heb vanmorgen telefonisch contact gehad met waarbij ik de uitslag van de scopie van afgelop...
4131,2799,"Hallo [PERSOON], Ik heb denk ik iets gemist, welke volgende stap is er genomen, maandag 23 maart...","Ik heb denk ik iets gemist, welke volgende stap is er genomen, maandag 23 maart ga ik naar het d..."
10084,6551,(incl. potje ontlasting inleveren),(incl. potje ontlasting inleveren)
10599,6922,Ik wacht vol spanning morgen ( het derde infuus incl. Bloedprikken en ontlasting inleveren ) af.,Ik wacht vol spanning morgen ( het derde infuus incl. Bloedprikken en ontlasting inleveren ) af.
11352,7474,Woensdag 4x naar de wc geweest (incl. snachts) en gisteren 3x.,Woensdag 4x naar de wc geweest (incl. snachts) en gisteren 3x.
16330,10791,"Hallo [PERSOON] en [PERSOON], Ik ben zaterdag 12 oktober volledig gestopt met de Budenofalk (in...","en , Ik ben zaterdag 12 oktober volledig gestopt met de Budenofalk (incl. afbouw natuurlijk)."
17300,11522,Kan ik dan 23e januari bloed gaan prikken incl. ontlasting check en bloedspiegel of beter de 30...,Kan ik dan 23e januari bloed gaan prikken incl. ontlasting check en bloedspiegel of beter de 30...
18164,12084,De afspraak was om over een half jaar een afspraak in te plannen ter controle inclusief bloed en...,De afspraak was om over een half jaar een afspraak in te plannen ter controle inclusief bloed en...
18172,12089,"De afspraak was om over een half jaar, dus rond april/mei 2021 een afspraak in te plannen ter co...","De afspraak was om over een half jaar, dus rond april/mei 2021 een afspraak in te plannen ter co..."
18227,12139,"Hi, Ik heb sinds vorige week, bij alles wat ik eet, moet ik dringend naar de wc, en is altijd ...","Ik heb sinds vorige week, bij alles wat ik eet, moet ik dringend naar de wc, en is altijd dunne ..."
25830,17541,"Dit heb ik gedaan, maar ik krijg nu erge symptomen inclusief helderrood bloedverlies.","Dit heb ik gedaan, maar ik krijg nu erge symptomen inclusief helderrood bloedverlies."
27292,18612,"- Stoelgang ruim meer dan 15 x per dag, incl. de slaaptijd.","Stoelgang ruim meer dan 15 x per dag, incl. de slaaptijd."
27989,18946,Ben erg misselijk inclusief braakneigingen en heb last van mijn buik (geblubber en buikloop).,Ben erg misselijk inclusief braakneigingen en heb last van mijn buik (geblubber en buikloop).
28624,19229,Ik heb sinds vandaag weer hevige buikklachten inclusief buikloop.,Ik heb sinds vandaag weer hevige buikklachten inclusief buikloop.
29974,20089,"Hoi, Zouden jullie mij een formulier voor het bloedprikken (inclusief testen op ijzerwaardes) en...",Zouden jullie mij een formulier voor het bloedprikken (inclusief testen op ijzerwaardes) en voor...
34504,23325,Kunnen jullie mij nieuwe formulieren incl potje toesturen om begin oktober wederom te laten prik...,Kunnen jullie mij nieuwe formulieren incl potje toesturen om begin oktober wederom te laten prik...
40673,28124,"Hallo dames, Ik heb een flinke keelontsteking incl oren dicht en neusverkoudheid, mag ik iets z...","dames, Ik heb een flinke keelontsteking incl oren dicht en neusverkoudheid, mag ik iets zwaarde..."

In [105]:
# one more time print <15 char clean_sentence
sentence_df[sentence_df["Clean_Sentence"].str.len() <= 15]

       Message_ID                        Sentence   Clean_Sentence
38             13            [APOTHEEK] [LOCATIE]       [APOTHEEK]
40             16                  HARTELIJK DANK   HARTELIJK DANK
60             32  Fijne dag  Groetjes, [PERSOON]        Fijne dag
63             33                  Nog een vraag?   Nog een vraag?
65             33                     Klopt dit ?      Klopt dit ?
...           ...                             ...              ...
45417       32585                Vr gr  [PERSOON]               Vr
45420       32589               Vr gr , [PERSOON]               Vr
45439       32611                 Alvast bedankt.  Alvast bedankt.
45440       32613                        Bedankt!         Bedankt!
45470       32631                   Merci alvast.    Merci alvast.

[4356 rows x 3 columns]

In [108]:
sentence_df = sentence_df[sentence_df["Clean_Sentence"].str.len() > 15]
sentence_df

,Message_ID,Sentence,Clean_Sentence
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hart...,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen."
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten."
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn."
...,...,...,...
45494,32679,"Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan.","Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan."
45495,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...
45496,32679,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?
45497,32681,"Hoi [PERSOON], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Oke, dat is iig al een geruststelling ik wacht de uitslag even af verder."
45498,32681,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!

In [109]:
sentence_df = sentence_df.reset_index(drop=True)
sentence_df["Sentence_ID"] = sentence_df.index + 1

In [110]:
sentence_df

,Message_ID,Sentence,Clean_Sentence,Sentence_ID
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hart...,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.,1
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.",2
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.,3
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten.",4
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.",5
...,...,...,...,...
41138,32679,"Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan.","Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan.",41139
41139,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te mak...,41140
41140,32679,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?,41141
41141,32681,"Hoi [PERSOON], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Oke, dat is iig al een geruststelling ik wacht de uitslag even af verder.",41142
41142,32681,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!,41143

In [111]:
sentence_df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/sentence_data_new.xlsx")

### Now run the translate_sentences script and then come back

In [60]:
# read the translated df
translated_sentence_df = pd.read_excel("/workspace/mijnidbcoachnlp/data/analysis_data/translated_sentence_data_new.xlsx", index_col=0)
translated_sentence_df

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence,Sentence_ID
0,3,Ik ben 2 weken geleden met spoed opgenomen in ...,Ikben2wekengeledenmetspoedopgenomeninhetinmetv...,I was rushed into the [PRESSION] two weeks ago...,1
1,3,"Ik kreeg acuut een pijnlijke druk op de borst,...",Ikkreegacuuteenpijnlijkedrukopdeborstschouderb...,I was acutely under a painful pressure on the ...,2
2,3,Het begon 1 uur na het avondeten.,Hetbegon1uurnahetavondeten,It started 1 hour after dinner.,3
3,3,"Ik had al de hele dag migraine, had dus ook we...",Ikhadaldeheledagmigrainehaddusookweiniggegeten,"I had migraines all day, so I hadn't eaten much.",4
4,3,"Ik werd heel erg misselijk, braakneigingen, du...",Ikwerdheelergmisselijkbraakneigingenduizeligen...,"I got very nauseous, vomiting, dizzy and rejuv...",5
...,...,...,...,...,...
41263,32679,"Ze hebben de urine op kweek gezet, kan morgenv...",Zehebbendeurineopkweekgezetkanmorgenvroegdeuit...,"They've put the urine on culture, can get the ...",41264
41264,32679,Afgelopen jaren is er al vaker bloed in mijn u...,Afgelopenjareniseralvakerbloedinmijnurinegevon...,"In recent years, blood has been found in my ur...",41265
41265,32679,Wat adviseert u hiermee te doen?,Watadviseertuhiermeetedoen,What do you suggest you do with this?,41266
41266,32681,"Hoi [PERSOON], Oke, dat is iig al een gerustst...",Okedatisiigaleengeruststellingikwachtdeuitslag...,"Hi [PRESSON], Okay, that's a relief;) I'll wai...",41267
41267,32681,Dankjewel voor de snelle reactie!,Dankjewelvoordesnellereactie,Thank you for the quick response!,41268

In [61]:
import pandas as pd
# Reset index to ensure alignment before comparison
sentence_df = sentence_df.reset_index(drop=True)
translated_sentence_df = translated_sentence_df.reset_index(drop=True)

# Find the first index where the two DataFrames differ
for i, (sent1, sent2) in enumerate(zip(sentence_df["Sentence"], translated_sentence_df["Sentence"])):
    if sent1 != sent2:
        print(f"First difference at index: {i}")
        break
else:
    print("No differences found!")

First difference at index: 659

In [77]:
pd.set_option("max_colwidth", None)
sentence_df[657:661]

,Message_ID,Sentence,Clean_Sentence
657,437,Verleden keer heb ik niet meegedaan omdat ik toch bij jullie onder behandeling ben.,Verleden keer heb ik niet meegedaan omdat ik toch bij jullie onder behandeling ben.
658,437,Wat is eigenlijk jullie advies t.b.v. jullie patiënten?,Wat is eigenlijk jullie advies t.b.v. jullie patiënten?
659,440,Bedankt voor de reactie; Ik laat t.z.t. ondertussen heb ik uitslag van het BVO ontvangen: dat is gelukkig gunstig.,Bedankt voor de reactie; Ik laat t.z.t. ondertussen heb ik uitslag van het BVO ontvangen: dat is gelukkig gunstig.
660,443,"[PERSOON], ik ben weer aan mijn laatste potje purinethol toe.",ik ben weer aan mijn laatste potje purinethol toe.

In [76]:
pd.set_option("max_colwidth", None)
translated_sentence_df[657:661]

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence,Sentence_ID
657,437,Verleden keer heb ik niet meegedaan omdat ik toch bij jullie onder behandeling ben.,Verledenkeerhebiknietmeegedaanomdatiktochbijjullieonderbehandelingben,Last time I didn't participate because I'm being treated with you guys.,658
658,437,Wat is eigenlijk jullie advies t.b.v. jullie patiënten?,Watiseigenlijkjullieadviestbvjulliepatinten,What exactly is your advice to your patients?,659
659,437,jullie patiënten?,julliepatinten,Your patients?,660
660,440,Bedankt voor de reactie; Ik laat t.z.t. ondertussen heb ik uitslag van het BVO ontvangen: dat is gelukkig gunstig.,BedanktvoordereactieIklaattztondertussenhebikuitslagvanhetBVOontvangendatisgelukkiggunstig,Thanks for the comment; I am late to receive results from the BVO in the meantime: that is fortunately beneficial.,661

In [78]:

translated_sentence_df.drop(index=659, inplace=True)
translated_sentence_df[657:661]

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence,Sentence_ID
657,437,Verleden keer heb ik niet meegedaan omdat ik toch bij jullie onder behandeling ben.,Verledenkeerhebiknietmeegedaanomdatiktochbijjullieonderbehandelingben,Last time I didn't participate because I'm being treated with you guys.,658
658,437,Wat is eigenlijk jullie advies t.b.v. jullie patiënten?,Watiseigenlijkjullieadviestbvjulliepatinten,What exactly is your advice to your patients?,659
660,440,Bedankt voor de reactie; Ik laat t.z.t. ondertussen heb ik uitslag van het BVO ontvangen: dat is gelukkig gunstig.,BedanktvoordereactieIklaattztondertussenhebikuitslagvanhetBVOontvangendatisgelukkiggunstig,Thanks for the comment; I am late to receive results from the BVO in the meantime: that is fortunately beneficial.,661
661,443,"[PERSOON], ik ben weer aan mijn laatste potje purinethol toe.",ikbenweeraanmijnlaatstepotjepurinetholtoe,"[PERSON], I'm back to my last jar of purinethol.",662

In [79]:
clean_sentences = sentence_df["Clean_Sentence"].to_list()
len(clean_sentences)

41267

In [80]:
translated_sentence_df["Clean_Sentence"] = clean_sentences

In [26]:
# Find sentences <15 characters
translated_sentence_df[translated_sentence_df["Clean_Sentence"].str.len() < 15]

Empty DataFrame
Columns: [Message_ID, Sentence, Clean_Sentence, Translated_Sentence, Sentence_ID]
Index: []

In [81]:
translated_sentence_df

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence,Sentence_ID
0,3,Ik ben 2 weken geleden met spoed opgenomen in het [PERSOON] in [LOCATIE] met verdenking van hartklachten.,Ik ben 2 weken geleden met spoed opgenomen in het in met verdenking van hartklachten.,I was rushed into the [PRESSION] two weeks ago in [LOCATION] with suspicion of heart problems.,1
1,3,"Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","Ik kreeg acuut een pijnlijke druk op de borst, schouderbladen, uitstralend naar de armen.","I was acutely under a painful pressure on the chest, shoulder blades, radiating to the arms.",2
2,3,Het begon 1 uur na het avondeten.,Het begon 1 uur na het avondeten.,It started 1 hour after dinner.,3
3,3,"Ik had al de hele dag migraine, had dus ook weinig gegeten.","Ik had al de hele dag migraine, had dus ook weinig gegeten.","I had migraines all day, so I hadn't eaten much.",4
4,3,"Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","Ik werd heel erg misselijk, braakneigingen, duizelig en oprispingen.En vreselijke pijn.","I got very nauseous, vomiting, dizzy and rejuvenating, and terrible pain.",5
...,...,...,...,...,...
41263,32679,"Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan.","Ze hebben de urine op kweek gezet, kan morgenvroeg de uitslag krijgen hiervan.","They've put the urine on culture, can get the results of this in the morning.",41264
41264,32679,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te maken heeft met de ziekte v Crohn of een fist oid?,Afgelopen jaren is er al vaker bloed in mijn urine gevonden en ik vraag me af of het iets te maken heeft met de ziekte v Crohn of een fist oid?,"In recent years, blood has been found in my urine and I wonder if it has anything to do with the disease v Crohn or a fist oid?",41265
41265,32679,Wat adviseert u hiermee te doen?,Wat adviseert u hiermee te doen?,What do you suggest you do with this?,41266
41266,32681,"Hoi [PERSOON], Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Oke, dat is iig al een geruststelling ;) ik wacht de uitslag even af verder.","Hi [PRESSON], Okay, that's a relief;) I'll wait for the results.",41267
41267,32681,Dankjewel voor de snelle reactie!,Dankjewel voor de snelle reactie!,Thank you for the quick response!,41268

In [83]:
# Find rows where 'Column1' does NOT start with a letter
filtered_df = translated_sentence_df[~translated_sentence_df["Clean_Sentence"].str.match(r'^[A-Za-z0-9]', na=False)]

filtered_df[50: 100]

,Message_ID,Sentence,Clean_Sentence,Translated_Sentence,Sentence_ID
1393,1091,"(ik ben met vakantie eind juli tot en met 12 augustus, dus met voldoende voorraad overbrug ik dat zonder problemen).","(ik ben met vakantie eind juli tot en met 12 augustus, dus met voldoende voorraad overbrug ik dat zonder problemen).","(I am on holiday at the end of July until 12 August, so with sufficient stock I bridge it without any problems).",1394
1402,1097,"Beste [PERSOON]/[PERSOON]/[PERSOON], Ik heb twee vragen.","//, Ik heb twee vragen.","Dear [PERSON]/[PERSON]/[PERSON], I have two questions.",1403
1415,1097,"(mocht de poli-afspraak verschoven worden naar een andere datum dan liefst pas na 11.15 uur) groet, HUM [PERSOON] [DATUM] [TELEFOONNUMMER]",(mocht de poli-afspraak verschoven worden naar een andere datum dan liefst pas na 11.15 uur) HUM,(If the policy appointment is postponed to another date than preferably after 11.15 p.m.) greets HUM [PRESSON] [DATE] [PHONE NUMBER],1416
1416,1099,"Beste [PERSOON]/[PERSOON]/[PERSOON], Eind juli vertrek ik met vakantie naar [LOCATIE].","//, Eind juli vertrek ik met vakantie naar .","Dear [PERSOON]/[PERSOON]/[PERSOON], At the end of July I leave for [LOCATION].",1417
1419,1101,"Beste [PERSOON]/[PERSOON]/[PERSOON], Ik heb vragen over mijn medicijngebruik met betrekking tot zwangerschap: Zijn er risico's gezien mijn medicijngebruik Prednisolon en Vedolizumab als mijn vriendin zwanger zou worden?","//, Ik heb vragen over mijn medicijngebruik met betrekking tot zwangerschap: Zijn er risico's gezien mijn medicijngebruik Prednisolon en Vedolizumab als mijn vriendin zwanger zou worden?","Dear [PERSOON]/[PERSOON]/[PERSOON], I have questions about my drug use regarding pregnancy: Are there any risks considering my drug use Prednisolone and Vedolizumab if my girlfriend would become pregnant?",1420
1421,1102,"Beste [PERSOON]/[PERSOON]/[PERSOON], Meestal volgt er een snelle reactie van uw kant als ik een vraag stel via ibd-coach, dit keer niet, wellicht vakantie?","//, Meestal volgt er een snelle reactie van uw kant als ik een vraag stel via ibd-coach, dit keer niet, wellicht vakantie?","Dear [PERSOON]/[PERSOON]/[PERSOON], is there usually a quick response from your side when I ask a question via ibd coach, not this time, perhaps vacation?",1422
1430,1103,"(met zelfde tijdstip als de 21e) groet, HUM [PERSOON] [DATUM] [TELEFOONNUMMER]",(met zelfde tijdstip als de 21e) HUM,(at the same time as the 21st) greets HUM [PRESSON] [DATE] [PHONE NUMBER],1431
1431,1105,"Beste [PERSOON] / [PERSOON] / [PERSOON], Luisterend naar mijn lichaam is het verstandiger om een langzamer afbouwtempo prednisolon aan te houden.","/ / , Luisterend naar mijn lichaam is het verstandiger om een langzamer afbouwtempo prednisolon aan te houden.","Dear [PERSON] / [PERSON] / [PERSON], Listening to my body it is wiser to maintain a slower phasing-out tempo prednisolone.",1432
1436,1107,"Beste [PERSOON] / [PERSOON] / [PERSOON], De huisarts heeft een oogzalf voorgeschreven vanwege een dik ooglid, dit ter voorkoming van ontsteking.","/ / , De huisarts heeft een oogzalf voorgeschreven vanwege een dik ooglid, dit ter voorkoming van ontsteking.","Dear [PERSOON] / [PERSOON] / [PERSOON], The GP prescribed an eye ointment because of a thick eyelid, this to prevent inflammation.",1437
1440,1109,"Beste [PERSOON]/[PERSOON]/[PERSOON], Ik ben bijna door mijn voorraad Prednisolon (15 mg per dag) en door mijn voorraad TacalD3 kauwtabletten heen.","//, Ik ben bijna door mijn voorraad Prednisolon (15 mg per dag) en door mijn voorraad TacalD3 kauwtabletten heen.","Best [PERSOON]/[PERSOON]/[PERSOON], I'm almost out of stock Prednisolone (15 mg per day) and through my supply of TacalD3 chewable tablets.",1441
1443,1111,"Beste [PERSOON]/ [PERSOON]/ [PERSOON], Op 10 januari aanstaande staat een scopie gepland, en daarna op 21 januari een poli-afspraak.","/ / , Op 10 januari aanstaande staat een scopie gepland, en daarna op 21 januari een poli-afspraak.","Dear [PERSOON]/ [PERSOON]/ [PERSOON], On January 10th, a scopy is planned, and then on January 21st, a political appointment.",1444
1446,1114,"Beste [PERSOON]/[PERSOON]/[PERSOON], Ik ben bijna door mijn voorraad Prednisolon (15 mg per dag) en door mijn voorraad TacalD3 kauwtabletten heen.","//, Ik ben bijna door mijn voorraad Prednisolon (15 mg per dag) en door mijn voorraad TacalD3 kauwtabletten heen.","Best [PERSOON]/[PERSOON]/[PERSOON], I'm almost out of stock Prednisolone (15 mg per day) and through my supply of TacalD3 chewable tablets.",1447
1449,1116,"Beste [PERSOON]/[PERSOON]/[PERSOON], Ik heb enkele huidschimmelplekjes op mijn bovenlichaam en mijn huisarts heeft een creme voorgeschreven: ketoconazol 20mg/g Op de bijsluiter van Xeljanz wordt aangegeven dat geneesmiddel ketoconazol bij orale toediening besproken moet worden met arts.","//, Ik heb enkele huidschimmelplekjes op mijn bovenlichaam en mijn huisarts heeft een creme voorgeschreven: ketoconazol 20mg/g Op de bijsluiter van Xeljanz wordt aangegeven dat geneesmiddel ketoconazol bij orale toediening besproken moet worden met arts.","Dear [PERSOON]/[PERSOON]/[PERSOON], I have some skin mold spots on my upper body and my GP has prescribed a cream: ketoconazole 20mg/g The package leaflet of Xeljanz states that medicinal product ketoconazole should be discussed with the physician on oral administration.",1450
1457,1122,"Beste [PERSOON]/[PERSOON]/[PERSOON], Sinds 5 juni ben ik klaar met de afbouw prednisolon.","//, Sinds 5 juni ben ik klaar met de afbouw prednisolon.","Dear [PERSOON]/[PERSOON]/[PERSOON], Since June 5th I have finished finishing prednisolone.",1458
1471,1128,"Beste [PERSOON]/[PERSOON]/[PERSOON], Donderdag [DATUM] staat een scopie gepland.","//, Donderdag staat een scopie gepland.","Dear [PERSOON]/[PERSOON]/[PERSOON], Thursday [DATUM] is scheduled for a scopy.",1472
1593,1222,"Hoi [PERSON], De klachten zijn wisselend.","[PERSON], De klachten zijn wisselend.","Hi [PERSON], the complaints are variable.",1594
1624,1288,"hallo [PERSON],ik weet nou genoeg!","[PERSON],ik weet nou genoeg!","Hello [PERSON], I know enough!",1625
1668,1324,>2000 veel last van buikkrampen en diaree.,>2000 veel last van buikkrampen en diaree.,>2000 abdominal cramps and diarrhea.,1669
1782,1439,"[PERSOON]) betreffende Pentasa granulaat (4G sachet), 1x per dag 1 sachet.",") betreffende Pentasa granulaat (4G sachet), 1x per dag 1 sachet.","[PERSOON]) on Pentasa granules (4G sachet), 1x per day 1 sachet.",1783
1785,1441,"[PERSOON]) betreffende Pentasa granulaat (4G sachet), 1x per dag 1 sachet.",") betreffende Pentasa granulaat (4G sachet), 1x per dag 1 sachet.","[PERSOON]) on Pentasa granules (4G sachet), 1x per day 1 sachet.",1786
1789,1443,"[PERSOON]) betreffende Pentasa granulaat (4G sachet), 1x per dag 1 sachet?",") betreffende Pentasa granulaat (4G sachet), 1x per dag 1 sachet?","[PERSOON]) on Pentasa granules (4G sachet), 1x a day 1 sachet?",1790
1851,1491,"hoi [PERSON] ik wil je vertellen dat terug zwanger ben en hoe moet het nu verder met bloed prikken en zo ,ik ben morgen in het ziekhuis dus ik zo dan al bloedprikken als dat moet dan kan ik dat morgen even doen .ik ben er al om kwart voor 10 in het ziekkhuis groetjes [PERSON]","[PERSON] ik wil je vertellen dat terug zwanger ben en hoe moet het nu verder met bloed prikken en zo ,ik ben morgen in het ziekhuis dus ik zo dan al bloedprikken als dat moet dan kan ik dat morgen even doen .ik ben er al om kwart voor 10 in het ziekkhuis [PERSON]","Hi [PERSON] I want to tell you that I'm pregnant again and how are we supposed to continue with blood pricking and such , I'll be in the hospital tomorrow so I'll be able to do that tomorrow .I'll be there at a quarter to 10 in the hospital greetings [PERSON]",1852
1863,1504,groetjes [PERSON] [PERSON],[PERSON] [PERSON],Greetings [PERSON] [PERSON],1864
1870,1514,hoi [PERSON] ik heb heel veel pijn in mijn buik links onder en het komt met heel veel pijn scheuten en dan blijft het zuren en dan is het weer hart daar .dus ik weet niet wat het is .ik moet ook veel naar de wc groetjes [PERSON],[PERSON] ik heb heel veel pijn in mijn buik links onder en het komt met heel veel pijn scheuten en dan blijft het zuren en dan is het weer hart daar .dus ik weet niet wat het is .ik moet ook veel naar de wc [PERSON],Hi [PERSON] I have a lot of pain in my abdomen underneath left and it comes with a lot of pain shoots and then it stays acidic and then it's heart again there .so I don't know what it is .I also have to go to the toilet greetings [PERSON],1871
1873,1519,Hoi [PERSON] Heb je mijn bloed en ontlasting uitslag Groetje [PERSON],[PERSON] Heb je mijn bloed en ontlasting uitslag [PERSON],Hi [PERSON] Did you get my blood and stool rash Greetings [PERSON],1874
1920,1625,"Hoi [PERSON], Zou u een nieuw recept kunnen schrijven van de zofran 4mg.","[PERSON], Zou u een nieuw recept kunnen schrijven van de zofran 4mg.","Hi [PERSON], could you write a new recipe of the zofran 4mg.",1921
1928,1630,(Erytheem nodosum).,(Erytheem nodosum).,(Erythem nodosum).,1929
1930,1632,"Hoi [PERSON], Zondag [DATUM] om 10.30u heb ik de MRI scan.","[PERSON], Zondag om 10.30u heb ik de MRI scan.","Hi [PERSON], Sunday [DATUM] at 10:30 I have the MRI scan.",1931
1933,1634,"Hoi [PERSOON]/[PERSOON], Ik had gisteren een belafspraak staan met dokter [PERSOON] over de uitslag van de MRI en ik ben alweer niet gebeld geworden.","/, Ik had gisteren een belafspraak staan met dokter over de uitslag van de MRI en ik ben alweer niet gebeld geworden.","Hi [PERSOON]/[PERSOON], I had a phone call yesterday with doctor [PERSOON] about the MRI's results and I haven't been called again.",1934
1934,1637,"Beste [PERSOON]/[PERSOON], Ik ben vandaag bij [PERSOON] op de poli geweest en we hebben afgesproken dat ik met een antibiotica (dixocycline) kuur zou starten voor 2 weken.","/, Ik ben vandaag bij op de poli geweest en we hebben afgesproken dat ik met een antibiotica (dixocycline) kuur zou starten voor 2 weken.","Dear [PERSOON]/[PERSOON], I went to [PERSOON] today on the poli and we agreed that I would start an antibiotic (dixocycline) course for 2 weeks.",1935
1954,1642,(Ze zitten samen in 1 vruchtzak).,(Ze zitten samen in 1 vruchtzak).,(They're in one amniotic sac together).,1955
1958,1644,"Hoi [PERSON], Dankuwel!","[PERSON], Dankuwel!","Hi [PERSON], thank you!",1959
1967,1651,Hoi [PERSOON]/[PERSOON] jullie me een herhaal recept kunnen doorsturen van de tramadol.,/ jullie me een herhaal recept kunnen doorsturen van de tramadol.,Hi [PERSOON]/[PERSOON] you can send me a repeat prescription of the tramadol.,1968
1990,1663,"Beste [PERSOON]/[PERSOON], Ik heb hier thuis nog twee bloedprikformulieren (hematologie en klin.chemie) liggen, die ik van [PERSOON] heb gekregen de laatste keer dat ik bij haar op de poli was.","/, Ik heb hier thuis nog twee bloedprikformulieren (hematologie en klin.chemie) liggen, die ik van heb gekregen de laatste keer dat ik bij haar op de poli was.","Dear [PERSOON]/[PERSOON], I have two more blood-prick forms (haematology and klin.chemistry) at home, which I received from [PERSOON] the last time I was with her on the poli.",1991
1992,1663,(Ik weet ook niet meer wanneer ik voor het laatst bloed heb laten prikken).,(Ik weet ook niet meer wanneer ik voor het laatst bloed heb laten prikken).,(I also don't remember when I last had blood shot).,1993
1996,1665,"Beste [PERSOON]/[PERSOON], Ik heb al een paar dagen last van mijn keel.","/, Ik heb al een paar dagen last van mijn keel.","Dear [PERSON]/[PERSON], I've had a throat problem for a few days.",1997
2011,1671,"Beste [PERSOON]/[PERSOON], Ik trek toch weer even aan de bel want het blijft al een tijd niet lekker gaan met de Crohn.","/, Ik trek toch weer even aan de bel want het blijft al een tijd niet lekker gaan met de Crohn.","Dear [PERSOON]/[PERSOON], I'm going to make another call because it hasn't been working out with the Crohn for a while.",2012
2030,1671,(Zeker als zou blijken dat er toch extra behandeld moet worden).,(Zeker als zou blijken dat er toch extra behandeld moet worden).,(Definitely if it turns out that extra treatment is needed).,2031
2066,1690,********* Wat betreft de cardioloog is het gebruik van de betablokkers geen absolute noodzakelijkheid.,********* Wat betreft de cardioloog is het gebruik van de betablokkers geen absolute noodzakelijkheid.,"*********** As far as cardiologists are concerned, the use of beta blockers is not an absolute necessity.",2067
2109,1712,"Beste [PERSOON]/[PERSOON], Ik heb afgelopen week bloed laten prikken t.b.v. mijn gesprek met [PERSOON] maandag a.s. Kunnen jullie bevestigen dat de uitslag hiervan door [ZIEKENHUIS] [LOCATIE] aan jullie doorgegeven is?","/, Ik heb afgelopen week bloed laten prikken t.b.v. mijn gesprek met maandag a.s. Kunnen jullie bevestigen dat de uitslag hiervan door [ZIEKENHUIS] aan jullie doorgegeven is?","Dear [PERSON]/[PERSON], Last week I had blood stained for my conversation with [PERSON] Monday a.s. Can you confirm that the result of this was passed on to you by [SIGHT HOUSE] [LOCATION]?",2110
2118,1717,"Beste [PERSOON]/[PERSOON], Als het goed is is er weer een uitslag van een ontlasting-onderzoek per fax naar jullie onderweg (of al binnengekomen), afkomstig van [ZIEKENHUIS] [LOCATIE].","/, Als het goed is is er weer een uitslag van een ontlasting-onderzoek per fax naar jullie onderweg (of al binnengekomen), afkomstig van [ZIEKENHUIS] .","Dear [PERSoon]/[PERSON], If it is all right, there is another result of a stool examination by fax to you on your way (or already arrived), coming from [SIGHSHOUSE] [LOCATION].",2119
2151,1726,"Beste [PERSOON] / [PERSOON], Op 8 augustus a.s. heb ik een afspraak op de poli bij [PERSOON].","/ , Op 8 augustus a.s. heb ik een afspraak op de poli bij .","Dear [PERSOON] / [PERSOON], On August 8, I have an appointment on the policy at [PERSOON].",2152
2160,1729,"Beste [PERSOON]/[PERSOON], Op 29/8 heb ik een afspraak bij [PERSOON].","/, Op 29/8 heb ik een afspraak bij .","Dear [PERSOON]/[PERSOON], On 29/8 I have an appointment with [PERSOON].",2161
2167,1732,"Hallo [PERSOON]/[PERSOON], Weten jullie wat de uitslag is van de laatste calprotectine test, ca augustus dit jaar.","/, Weten jullie wat de uitslag is van de laatste calprotectine test, ca augustus dit jaar.","Hello [PERSOON]/[PERSOON], you know what the result of the last calprotectine test, ca August this year.",2168
2170,1736,"Beste [PERSOON]/[PERSOON], Ik heb sinds enige tijd wat last van mijn ogen en de laatste dagen zijn ze ook best rood en misschien dus zelfs wat ontstoken.","/, Ik heb sinds enige tijd wat last van mijn ogen en de laatste dagen zijn ze ook best rood en misschien dus zelfs wat ontstoken.","Dear [PERSOON]/[PERSOON], I have for some time had some trouble with my eyes and in the last few days they are also quite red and maybe even a bit inflamed.",2171
2180,1737,"Beste [PERSOON]/[PERSOON], Op 20 december jl.","/, Op 20 december jl.","Dear [PERSoon]/[PERSON], December 20th.",2181
2194,1746,"Hallo [PERSOON]/[PERSOON], Ik heb over een tijdje een afspraak met [PERSOON] op de poli en volgens mij heb ik bloedprikformulieren daartoe ontvangen.","/, Ik heb over een tijdje een afspraak met op de poli en volgens mij heb ik bloedprikformulieren daartoe ontvangen.","Hello [PERSOON]/[PERSOON], I have an appointment with [PERSOON] on the policy in a while and I think I have received blood injection forms for that.",2195
2196,1746,:( Is het te doen om een nieuwe set te sturen van de onderzoeken die nodig zijn (incl.,:( Is het te doen om een nieuwe set te sturen van de onderzoeken die nodig zijn (incl.,:( Is it possible to send a new set of the investigations needed (incl.,2197
2204,1749,"Hallo [PERSOON]/[PERSOON], Eerst ter info: De aanmelding t.a.v. Calprosmart lijkt gelukt.","/, Eerst ter info: De aanmelding t.a.v. Calprosmart lijkt gelukt.","Hello [PERSOON]/[PERSOON], First for information: The registration of Calprosmart seems to have been successful.",2205
2219,1756,"Hallo [PERSOON]/[PERSOON], Even reagerend op het laatste bericht van [PERSOON] waarin staat ""al dan niet de medicatie aan te passen"".","/, Even reagerend op het laatste bericht van waarin staat ""al dan niet de medicatie aan te passen"".","Hello [PERSOON]/[PERSOON], Responding to the last message of [PERSOON] stating ""whether or not to change the medication.""",2220

In [33]:
translated_sentence_df.to_excel("/workspace/mijnidbcoachnlp/data/analysis_data/translated_sentence_data_new.xlsx")